import { TopTrumpType } from "./types";

const cards: TopTrumpType[] = [
  {
    name: "Robol",
    image: "./monsters/IMG_20200708_175719.jpg",
    description: "he looks like a kangaroo in a jersey!",
    power: 9,
    speed: 8,
    cuteness: 1,
    sillyness: 0,
  },
  {
    name: "Tonguey",
    image: "./monsters/IMG_20200708_175832.jpg",
    description: "he can use his tongue to speak, lick and clean carpets!",
    power: 7,
    speed: 9,
    cuteness: 2,
    sillyness: 0,
  },
  {
    name: "Doorbot",
    image: "./monsters/IMG_20200708_175858.jpg",
    description: "Actually two stacked on top of each other!",
    power: 3,
    speed: 5,
    cuteness: 7,
    sillyness: 4,
  },
  {
    name: "Sole-lee",
    image: "./monsters/IMG_20200708_180102.jpg",
    description: "Has 24 eyes and she can rotate and fly!",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Timey-Wimey",
    image: "./monsters/IMG_20200708_180214.jpg",
    description: "Has two tails like clock hands.",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Scattle",
    image: "./monsters/IMG_20200708_180258.jpg",
    description: "Likes to jump down plugholes!",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Look-throughticle",
    image: "./monsters/IMG_20200708_180429.jpg",
    description: "Can radar beam to Earth when on a weird planet.",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Rabarab the Rabbity",
    image: "./monsters/IMG_20200708_180516.jpg",
    description: "A big fan of stars!",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Dalek & baby Dalek",
    image: "./monsters/IMG_20200708_184619.jpg",
    description: "EX-GERMINATE!",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Crabbo",
    image: "./monsters/IMG_20200708_184648.jpg",
    description: "Has a target instead of an eye.",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Leg-Try",
    image: "./monsters/IMG_20200708_184901.jpg",
    description: "A tribute to a tatted triceratops!",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Tropiclem",
    image: "./monsters/IMG_20200709_105114.jpg",
    description:
      "She drifts in low gravity and can photosynthesise from methane. ",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Jumblemunch",
    image: "./monsters/IMG_20200709_110351.jpg",
    description: "Hello, Sweetie!",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Skatesnake",
    image: "./monsters/IMG_20200709_155957.jpg",
    description:
      "Forked tongue, sideways movement, flagbone, and fish antennae!",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Cupcrabflame",
    image: "./monsters/IMG_20200709_160349.jpg",
    description: "Can move its head to any side of its legs to roll along.",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Helmet Crab",
    image: "./monsters/IMG_0631.jpg",
    description:
      "Its horns are so neat you could almost think it was one piece of helmet.",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Boostbot",
    image: "./monsters/IMG_20200713_120345.jpg",
    description:
      "If one part explodes, the rest can sail away with the person safely!",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Sattlesat",
    image: "./monsters/IMG_20200713_120437.jpg",
    description: "He's a satellite. The dome is his eye-bomb",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Giant Anda",
    image: "./monsters/IMG_20200713_185830.jpg",
    description: "Uses logic to bamboozle!",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Sheriff of Not",
    image: "./monsters/IMG_20200713_185906.jpg",
    description: "Contradictory - true = false; false = true. ",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Truth of the Logic",
    image: "./monsters/IMG_20200713_185923.jpg",
    description: "He's a truth table, but alive!",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "Archgate",
    image: "./monsters/IMG_20200713_185935.jpg",
    description: "His eye is a output!",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
  {
    name: "RoboSquirrel",
    image: "./monsters/IMG_20200715_091758.jpg",
    description: "Wields a cyber-acorn and a hazel laser! ",
    power: 1,
    speed: 7,
    cuteness: 4,
    sillyness: 7,
  },
];

export default cards;
